server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  thymeleaf:
    cache: true

app:
  upload:
    dir: /opt/mathbank/uploads/problem
  admin:
    init-password: ${ADMIN_INIT_PASSWORD}

logging:
  level:
    com.mathbank: INFO
    org.mybatis: WARN
    org.springframework.security: WARN
